# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: alejandroa
service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs22.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:us-east-1:466089068750:table/usersTable

plugins:
  - serverless-offline
  - serverless-dynamodb

package:
  individually: true
  patterns:
    - "!.dynamodb"
    - "!.node_modules" # Usar Layers

custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  get-users:
    handler: getUsers/handler.getUsers
    events:
      - http:
          path: users/{id}
          method: GET
          cors: true

  create-users:
    handler: createUsers/handler.createUsers
    events:
      - http:
          path: users
          method: POST
          cors: true

  update-users:
    handler: updateUsers/handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
          cors: true

  delete-users:
    handler: deleteUsers/handler.deleteUsers
    events:
      - http:
          path: users/{id}
          method: DELETE
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
